### ISSUE TITLE
ART POC Tech Design

### ISSUE THREAD

**Issue by byrdsd** [byrdsd/art_poc#1]
## User Story

*As a* lesson creator

*I want* to be able to break content into readily consumable chunks, with different designs as appropriate to the type of content

*So that* I can create engaging educational content quickly and effectively

### Rails backend

- Administered at /admin
    - No auth required for POC
    - Blocks can be added, edited, deleted
        - Blocks require a title
    - Flashcard blocks
        - See all flashcards
        - Add new flashcard
            - Front body
            - Back body
        - Edit flashcard
        - Delete flashcard
        - Permit images
- GET at /block returns JSON-formatted Block content
- Starts in a Docker container

### React frontend

- API Helper
    - Abstracts GET requests for block content
- Home page
    - Renders 1 random block at the top of the page
    - Lists all other available blocks
- Block page
    - Opened from homepage list
    - Block content stands alone on the page
    - Back button at the bottom returns to the homepage
- React rendering and functionality
- Fully responsive blocks

## Architecture

We'll use a Rails backend with a React frontend running in Node. As there was no specification for the backend's admin interface beyond that it be functional, we'll start simple with static forms and iterate if we have time to make it more reactive.

Both the React frontend and Rails backend will utilize the /block endpoint for CRUD operations. API will follow RESTful design principles.

The Rails app will run in a Docker container, the node application will run as a standalone server.

## Subtasks

- [x]  Stand up Rails application in Docker
- [x]  Write Block API
- [x]  Write Rails admin
- [x]  Create flashcard styles
- [x]  Create flashcard React component
- [x]  Create pages
